### ISSUE TITLE
Add support for a `body` parameter in the config.yml file

### ISSUE THREAD

**Issue by prestonvasquez** [alpstable/gidari#153]
Some requests may require a request body, like so:

```yml
requests:
  - endpoint: x
    body: 
      INPUT: y
```

Use the following for an integration test:  https://documenter.getpostman.com/view/6065583/RzfmEmUY#87754d4c-3c52-44ac-bb70-a9027d23a02d

This will also require a documentation update to the README.md#Configuration section.
