### ISSUE TITLE
MongoDB will upsert data from the same request multiple times

### ISSUE THREAD

**Issue by prestonvasquez** [alpstable/gidari#154]
Use the following configuration as a starting point:

```yml
url: https://ghibliapi.herokuapp.com
connectionStrings:
  - mongodb://mongo1:27017/studio-ghibli
rateLimit:
  burst: 5
  period: 1
requests:
  - endpoint: /films
```

If you run gidari multiple times with this configuration, it will insert the payloads multiple times. This should not happen, the `mongo#Upsert` method needs to be modified to avoid this behavior.
