### ISSUE TITLE
Handle duplicate connection strings in configuration file

### ISSUE THREAD

**Issue by prestonvasquez** [alpstable/gidari#163]
A user could create a configuration file with duplicate connection strings like this:

```yml
url: https://official-joke-api.appspot.com
connectionStrings: 
  - mongodb://mongo1:27017/jokes
  - mongodb://mongo1:27017/jokes
rateLimit:
  burst: 5
  period: 1
requests:
  - endpoint: /random_joke
```

If this happens, we need to log a warning in `transport.Config#repos` that the user did this, and only create a repo for one of the connection strings.
