### ISSUE TITLE
Add transport support for arrays of strings

### ISSUE THREAD

**Issue by prestonvasquez** [alpstable/gidari#193]
Right now Gidari only supports arrays of objects or an object from HTTP request response bodies. However, a config file like this:

```yml
url: https://ron-swanson-quotes.herokuapp.com
connectionStrings:
  - mongodb://mongo1:27017/quotes
rateLimit:
  burst: 1
  period: 1
requests:
  - endpoint: /v2/quotes # returns ["some string"]
    table: ronswansons
```

would result in the following runtime error:

```
FATA[0000] error upserting data: failed to decode records: failed to decode records: failed to unmarshal json: proto: syntax error (line 1:1): unexpected token "I call this turf ‘n’ turf. It's a 16 oz T-bone and a 24 oz porterhouse. Also, whiskey and a cigar. I am going to consume all of this at the same time because I am a free American."
```

We need to add support for this case. One way to achieve this would be to add a new field to the `transport.Request` struct:

```go
type Request struct {
  // ArrayColumn is the name of the column to insert the response body as an array of values. 
  // This is not applicable to any  response body, only response bodies of the form 
  // "[ <value_1>, <value_2>, ... , <value_n> ]" where value_i is not an object.
  ArrayColumn string `yaml:"arrayColumn"`
}
```

Then in the config file we can do something like:

```yml
url: https://ron-swanson-quotes.herokuapp.com
connectionStrings:
  - mongodb://mongo1:27017/quotes
rateLimit:
  burst: 1
  period: 1
requests:
  - endpoint: /v2/quotes
    table: ronswansons
    arrayColumn: list
```

Then we'd expect the data structure to look like this:

```js
> db.ronswansons.find()
{ list: ["some string"] }
```
