### ISSUE TITLE
Warn if the response body is HTML

### ISSUE THREAD

**Issue by prestonvasquez** [alpstable/gidari#195]
It could happen that the response body to a request is HTML, a config like the following produces this result:

```yml
url: https://api.cryptonator.com
connectionStrings:
  - mongodb://mongo1:27017/cryptonator
rateLimit:
  burst: 1
  period: 1
requests:
  - endpoint: /api/ticker/btc-usd
    table: chtml
```

We need to add a new field to the `transport.Request` type called `ClobColumn`:

```go
type Request struct {
    // ClobColumn will be the name of the column in the table associated with the request to store Clobs of data such as HTML.
    ClobColumn string `yaml:"clobColumn"`
}
```

Then in the configuration a user can do this:

```yml
url: https://api.cryptonator.com
connectionStrings:
  - mongodb://mongo1:27017/cryptonator
rateLimit:
  burst: 1
  period: 1
requests:
  - endpoint: /api/ticker/btc-usd
    table: chtml
    clobColumn: data
```

Which would store the resulting HTML data into the "data" column of the "chtml" table. 

If the user does not provide the clobColumn and the response body is HTML the transport SHOULD NOT return a fatal, rather it should throw a Warn log with the message "response body for '/api/ticker/btc-usd' was HTML, discarding data since no 'clobColumn' was defined in the configuration file".
