### ISSUE TITLE
transactionExceededLifetimeLImitSeconds bug

### ISSUE THREAD

**Issue by prestonvasquez** [alpstable/gidari#60]
When running a long-standing query on mongodb, you get an error like this:

```
FATA[0061] error upserting data: (TransactionExceededLifetimeLimitSeconds) operation was interrupted because the transaction exceeded the configured 'transactionLifetimeLimitSeconds
```

Here is an example configuration:

```
url: https://api-public.sandbox.exchange.coinbase.com
authentication:
  apiKey:
    passphrase: ***
    key:  ***
    secret: ***
dnsList:
  - mongodb://mongo1:27017/coinbasepro
rateLimit:
  burst: 5
  period: 1
truncate: true
requests:
  - endpoint: /accounts
    method: GET
  - endpoint: /currencies
    method: GET
  - endpoint: /products
    method: GET
  - endpoint: /products/BTC-USD/stats
    method: GET
    table: btc_stats
  - endpoint: /products/BTC-USD/candles
    method: GET
    timeseries:
        startName: start
        endName: end
        period: 18000
        layout: "2006-01-02T15:04:05Z"
    query:
      granularity: "60"
      start: "2018-11-09T17:11:08Z"
      end: "2019-01-12T18:11:08Z"
```
